---
spring:
  config:
    activate:
      on-profile: default
server:
  port: 9000
eureka:
  instance:
    hostname: default-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

---
spring:
  config:
    activate:
      on-profile: peer-1
  application:
    name: eureka-server-clustered
server:
  port: 9001
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_2_URL:http://localhost:9002/eureka/},${PEER_3_URL:http://localhost:9003/eureka/}
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

---
spring:
  config:
    activate:
      on-profile: peer-2
  application:
    name: eureka-server-clustered
server:
    port: 9002
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_1_URL:http://localhost:9001/eureka/},${PEER_3_URL:http://localhost:9003/eureka/}
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

---
spring:
  config:
    activate:
      on-profile: peer-3
  application:
    name: eureka-server-clustered
server:
  port: 9003
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_1_URL:http://localhost:9001/eureka/},${PEER_2_URL:http://localhost:9002/eureka/}
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}
