---
spring:
  config:
    activate:
      on-profile: default
server:
  port: 9000  
eureka:
  instance:
    hostname: default-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  config:
    activate:
      on-profile: peer-1
  application:
    name: eureka-server-clustered
server:
  port: 9001
eureka:
  instance:
    hostname: peer-1-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_2_URL:http://peer-2-server.com:9002/eureka/},${PEER_3_URL:http://peer-3-server.com:9003/eureka/}

---
spring:
  config:
    activate:
      on-profile: peer-2
  application:
    name: eureka-server-clustered
server:
    port: 9002
eureka:
  instance:
    hostname: peer-2-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_1_URL:http://peer-1-server.com:9001/eureka/},${PEER_3_URL:http://peer-3-server.com:9003/eureka/}

---
spring:
  config:
    activate:
      on-profile: peer-3
  application:
    name: eureka-server-clustered
server:
  port: 9003
eureka:
  instance:
    hostname: peer-3-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${PEER_1_URL:http://peer-1-server.com:9001/eureka/},${PEER_2_URL:http://peer-2-server.com:9002/eureka/}
